probes:
  - name: latency
    type: std_fping
    output:
      - elastic_avg
      - elastic_loss

    public_dns:
      hosts:
        - host: 8.8.8.8
          name: Google
          color: red
        - host: 130.61.226.235
          name: random
          color: blue

plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    output:
      - elastic

  - name: elastic_loss
    type: elastic

    # will create one file per host
    # for example: latency-8.8.8.8-avg
    filename: "{source}-{host}-{field}"

    # specified which field to retrieve the value from
    field: loss

    # whisper configuration
    #aggregation_method: average
    #sparse: false
    #x_files_factor: 0.5
    #retention:
    #  - 3s:1d
    #  elastic configuration
    IP: 169.61.226.235
  - name: elastic_avg
    type: elastic

    # will create one file per host
    # for example: latency-8.8.8.8-avg
    filename: "{source}-{host}-{field}"

    # specified which field to retrieve the value from
    field: avg

    #  elastic configuration
    IP: 0.0.0.0

