probes:
  - name: latency
    type: std_fping
    output:
      - elastic_avg
      - elastic_loss

    public_dns:
      hosts:
        - host: 8.8.8.8
        - host: 4.2.2.1
        - host: 208.67.222.222

plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    output:
      - elastic

  - name: elastic_loss
    type: elastic

    # specified which field to retrieve the value from
    field: loss
    elastic_index: loss_index

    #  elastic configuration
    elastic_ip: 127.0.0.1

  - name: elastic_avg
    type: elastic

    # specified which field to retrieve the value from
    field: avg
    elastic_index: avg_index
    
    # specified which field to retrieve the value from

    #  elastic configuration
    elastic_ip: 127.0.0.1

